export type Publication = {
  publication_guid?: string | undefined;
  publication_key?: string;
  publication_id?: string;
  title?: string;
  abstract?: string;
  issue_identification?: string;
  originator?: string;
  series_name?: string;
  publication_year?: string;
  place_keyword_1?: string | null;
  place_keyword_2?: string | null;
  place_keyword_3?: string | null;
  place_keyword_4?: string | null;
  place_keyword_5?: string | null;
  theme_keyword_1?: string | null;
  theme_keyword_2?: string | null;
  theme_keyword_3?: string | null;
  theme_keyword_4?: string | null;
  theme_keyword_5?: string | null;
  bcgs_link?: string | null;
  pdf_link?: string | null;
  zip_link?: string | null;
  thumbnail_link?: string | null;
};
